#:include src/util/StringExtensions.cs
#:include src/config/Config.cs
#:include src/config/JsonContext.cs
#:include src/entity/Author.cs
#:include src/entity/Blog.cs
#:include src/entity/Category.cs
#:include src/domain/author/CreateAuthorDto.cs
#:include src/domain/author/UpdateAuthorDto.cs
#:include src/domain/author/AuthorResponseDto.cs
#:include src/domain/blog/CreateBlogDto.cs
#:include src/domain/blog/UpdateBlogDto.cs
#:include src/domain/blog/BlogResponseDto.cs
#:include src/domain/category/CreateCategoryDto.cs
#:include src/domain/category/UpdateCategoryDto.cs
#:include src/domain/category/CategoryResponseDto.cs
#:include src/data/AppDbContext.cs
#:include src/data/configurations/AuthorConfiguration.cs
#:include src/data/configurations/BlogConfiguration.cs
#:include src/data/configurations/CategoryConfiguration.cs
#:include src/repository/IAuthorRepository.cs
#:include src/repository/IBlogRepository.cs
#:include src/repository/ICategoryRepository.cs
#:include src/repository/AuthorRepository.cs
#:include src/repository/BlogRepository.cs
#:include src/repository/CategoryRepository.cs
#:include src/service/IAuthorService.cs
#:include src/service/IBlogService.cs
#:include src/service/ICategoryService.cs
#:include src/service/AuthorService.cs
#:include src/service/BlogService.cs
#:include src/service/CategoryService.cs
#:include src/handler/AuthorHandler.cs
#:include src/handler/BlogHandler.cs
#:include src/handler/CategoryHandler.cs
#:include src/handler/ExceptionHandler.cs
#:include src/middleware/logger.cs
